### ISSUE TITLE
** (FunctionClauseError) no function clause matching in :trie.store/3

### ISSUE THREAD

**Issue by gheorghina** [okeuday/trie#10]
Hi
Thumbs up for the library. I am trying to use trie in elixir from v1.7.4.

And I just created some small tests, in which I try your samples , and I noticed that for example :trie.new([{"abcdefghijklmnopqrstuvwxyz", 1},{"aac", 2}])  throws an exception:
 ** (FunctionClauseError) no function clause matching in :trie.store/3 in trie/src/trie.hrl:1005: :trie.store/3 

I also tried btrie, and this one is working. Maybe I am doing something wrong.

I tried the trie functionality in erlang shell and it is working, so it seams that it is crashing only in elixir ( I compiled the code before trying)

I have:
Erlang/OTP 21 and Elixir 1.7.3

Thank you,

**Comment by gheorghina** [comment]
My bad: I did not use the conversion to chars, I used "aac" instead of 'aac'

**Comment by okeuday** [comment]
Yeah, np, that is it.
