### ISSUE TITLE
find_prefixes/2 always returns an empty result set

### ISSUE THREAD

**Issue by Licenser** [okeuday/trie#6]
Not entirely sure weather this is me misusing it but I fail to get find_prefixes/2 to return any data other then an empty list.

```erlang
3> T1 = btrie:append(<<"this is a test year really!">>, t, btrie:new()).
{116,116,{{<<"his is a test year really!">>,[t]}}}
4> btrie:find_prefixes(<<"this">>, T1).
[]
5> btrie:find_prefix(<<"this">>, T1).
prefix
```

**Comment by okeuday** [comment]
As discussed on IRC, you wanted `btrie:fetch_keys_similar(<<"this">>, T1)`.

**Comment by Licenser** [comment]
sorry for not closing it myself, got squirrel-ed ...
