### ISSUE TITLE
Wrong behavior of trie:is_prefixed/2 ?

### ISSUE THREAD

**Issue by fxmy** [okeuday/trie#7]
Hi,
  Just encountered some weird behaviors of trie:is_prefixed/2.
```erlang
76> Foo = trie:store("abc",value,trie:new()).
{97,97,{{"bc",value}}}
77> trie:is_prefixed("abcdefghijk",Foo).     
false

78> Bar = trie:store("abcd",value,Foo).      
{97,97,
 {{{98,98,{{{99,99,{{{100,100,{{[],value}}},value}}},error}}},
   error}}}
79> trie:is_prefixed("abcdefghijk",Bar).     
true
```
Although utterly unfamiliar with trie, is this behavior intended?
Or I'm just using it wrong? :joy: 

After a little source code digging, it seems like [L625-626](https://github.com/okeuday/trie/blob/master/src/trie.erl#L625-L626) only matches when calling `trie:is_prefixed(Key,Trie)` with a pre-existing `Key` in `Trie`, which is essentially calling
```erlang
trie:is_prefixed("abc",Foo).
```
Maybe change it to this?
```erlang
{MaybePreT, _} ->
    case lists:prefix(MaybePreT,T) of true -> true; false -> false end;
```
Will this break the properties of trie? :joy: 

FYC, some tracing messages:
```erlang
7> trie:is_prefixed("abc",Foo).
(<0.41.0>) call trie:is_prefixed("abc",{97,97,{{"bc",value}}})
(<0.41.0>) returned from trie:is_prefixed/2 -> true
true

8> trie:is_prefixed("abcdefghijk",Foo).                                                                                   
(<0.41.0>) call trie:is_prefixed("abcdefghijk",{97,97,{{"bc",value}}})
(<0.41.0>) returned from trie:is_prefixed/2 -> false
false

9> trie:is_prefixed("abcdefghijk",Bar).     
(<0.41.0>) call trie:is_prefixed("abcdefghijk",{97,97,{{{98,98,{{{99,99,{{{100,100,{{[],value}}},value}}},error}}},error}}})
(<0.41.0>) call trie:is_prefixed("bcdefghijk",{98,98,{{{99,99,{{{100,100,{{[],value}}},value}}},error}}})
(<0.41.0>) call trie:is_prefixed("cdefghijk",{99,99,{{{100,100,{{[],value}}},value}}})
(<0.41.0>) returned from trie:is_prefixed/2 -> true
(<0.41.0>) returned from trie:is_prefixed/2 -> true
(<0.41.0>) returned from trie:is_prefixed/2 -> true
true
```

**Comment by okeuday** [comment]
@fxmy Thank you for finding this problem!  There is a related problem too:

    false = trie:is_prefixed("abcdefghijk", Foo).
    false = trie:is_prefix("a", Foo).

Both should be returning true.  I added a fix for this, which includes what you suggested for is_prefixed/2 but more minimal (since the case isn't required).  Thanks!

**Comment by fxmy** [comment]
I must have been drunk to write `case E of true->true;` :laughing: 
Thanks for the quick response~⎝( OωO)⎠
